# Generated by Django 4.1.5 on 2023-01-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RxcuiNdc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rxcui', models.PositiveBigIntegerField()),
                ('ndc', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('rxcui', 'ndc')},
            },
        ),
    ]
